services:
  - type: web
    name: pixxlverse
    env: node
    buildCommand: yarn && cd types && yarn && cd ../server && tsc --project tsconfig.server.json
    startCommand: cd server/lib && node index.js
    envVars:
      - key: PORT
        value: 10000
    plan: free 